export const branchSeedData = [
  {
    name: "Family Blessing Bali",
    slug: "family-blessing-bali",
    type: "ONSITE",
    city: "Denpasar",
    province: "Bali",
    country: "Indonesia",
    venueName: "Mahajaya Agung Hotel",
    address: "Jln Cokroaminoto 63, Denpasar - Bali",
    contactPersonName: "Ibu Lidia",
    contactPersonPhone: "081276615993",
    whatsappPhone: "6281276615993",
    bankName: "BCA",
    bankAccountNumber: "1462417939",
    bankAccountHolder: "Nike Hardo Christanty",
    youtubeChannelName: "Family Blessing Bali New",
  },
  {
    name: "Family Blessing Bandung",
    slug: "family-blessing-bandung",
    type: "ONSITE",
    city: "Bandung",
    province: "Jawa Barat",
    country: "Indonesia",
    venueName: "Graha Arkana Lt. 1",
    address: "Graha Arkana Lt. 1, area Pasar Kaliki Hypersquare",
    contactPersonName: "Hendro",
    contactPersonPhone: "081188030156",
    whatsappPhone: "6281188030156",
    bankName: "BCA",
    bankAccountNumber: "0084283335",
    bankAccountHolder: "Jonathan / Hendro Wijaya",
    youtubeChannelName: "Family Blessing Bandung",
  },
  {
    name: "Family Blessing Jakarta",
    slug: "family-blessing-jakarta",
    type: "ONSITE",
    city: "Jakarta Utara",
    province: "DKI Jakarta",
    country: "Indonesia",
    venueName: "KTC Kelapa Gading, Lt. 2 Hall Gift Center",
    address: "KTC Kelapa Gading, Lt. 2 Hall Gift Center, Jakarta Utara",
    contactPersonName: "Sarah",
    contactPersonPhone: "081808240660",
    whatsappPhone: "6281808240660",
    bankName: "BCA",
    bankAccountNumber: "4280605137",
    bankAccountHolder: "Nathasya / Jonathan",
    youtubeChannelName: "Family Blessing Jakarta",
  },
  {
    name: "Family Blessing Surabaya",
    slug: "family-blessing-surabaya",
    type: "ONSITE",
    city: "Surabaya",
    province: "Jawa Timur",
    country: "Indonesia",
    venueName: "Hotel Bumi Surabaya, Isyanna Ballroom Lt. 2",
    address: "Hotel Bumi Surabaya, Isyanna Ballroom Lt. 2",
    contactPersonName: "Bp Robby",
    contactPersonPhone: "0813030185",
    whatsappPhone: "62813030185",
    bankName: "BCA",
    bankAccountNumber: "5060274004",
    bankAccountHolder: "Juniati",
    youtubeChannelName: "Family Blessing Surabaya",
  },
  {
    name: "Family Blessing Yogyakarta",
    slug: "family-blessing-yogyakarta",
    type: "ONSITE",
    city: "Yogyakarta",
    province: "DI Yogyakarta",
    country: "Indonesia",
    venueName: "Hotel Merapi Merbabu",
    address: "Hotel Merapi Merbabu, Jln Raya Seturan",
    contactPersonName: "Bp Andrew",
    contactPersonPhone: "0817274950",
    whatsappPhone: "62817274950",
    bankName: "BCA",
    bankAccountNumber: "4565119100",
    bankAccountHolder: "Andrew Pardede",
    youtubeChannelName: "Family Blessing Yogyakarta",
  },
  {
    name: "Family Blessing Semarang",
    slug: "family-blessing-semarang",
    type: "ONSITE",
    city: "Semarang",
    province: "Jawa Tengah",
    country: "Indonesia",
    venueName: "Hotel Muria - Ballroom Hotel",
    address: "Hotel Muria - Ballroom Hotel, Jln DR. Cipto, Semarang",
    contactPersonName: "Bp Franky",
    contactPersonPhone: "0818298284",
    whatsappPhone: "62818298284",
    bankName: "BCA",
    bankAccountNumber: "2461391399",
    bankAccountHolder: "Ita Istiyani Prasetyowati",
    youtubeChannelName: "Family Blessing Semarang",
  },
  {
    name: "Family Blessing Purwokerto",
    slug: "family-blessing-purwokerto",
    type: "ONSITE",
    city: "Purwokerto",
    province: "Jawa Tengah",
    country: "Indonesia",
    venueName: "Grand Karlita Hotel - Ruang Saphire Lt. 2",
    address: "Grand Karlita Hotel - Ruang Saphire Lt. 2, Purwokerto",
    contactPersonName: "Ibu Agung",
    contactPersonPhone: "081391855288",
    whatsappPhone: "6281391855288",
    bankName: "BCA",
    bankAccountNumber: "3586800004",
    bankAccountHolder: "Junsuari R / Irene W",
    youtubeChannelName: "Family Blessing Purwokerto",
  },
  {
    name: "Family Blessing Malang",
    slug: "family-blessing-malang",
    type: "ONSITE",
    city: "Malang",
    province: "Jawa Timur",
    country: "Indonesia",
    venueName: "Hotel Trio Indah 2 - Hall Lt. 2",
    address: "Hotel Trio Indah 2 - Hall Lt. 2, Malang",
    contactPersonName: "Bp Dony",
    contactPersonPhone: "081358842912",
    whatsappPhone: "6281358842912",
    bankName: "BCA",
    bankAccountNumber: "6225006737",
    bankAccountHolder: "Donny Sunjaya",
    youtubeChannelName: "Family Blessing Malang",
  },
  {
    name: "Family Blessing Batam",
    slug: "family-blessing-batam",
    type: "ONSITE",
    city: "Batam",
    province: "Kepulauan Riau",
    country: "Indonesia",
    venueName: "Hotel AsiaLink - Ruang Clove Lt. 1",
    address: "Hotel AsiaLink - Ruang Clove Lt. 1, depan Hotel Aston Pelita",
    contactPersonName: "Ibu Jeanne",
    contactPersonPhone: "085363113328",
    whatsappPhone: "6285363113328",
    bankName: "BCA",
    bankAccountNumber: "8520093878",
    bankAccountHolder: "Susilawati Jeanne Sindoro",
    youtubeChannelName: "Fambless Batam",
  },
  {
    name: "Family Blessing Manado",
    slug: "family-blessing-manado",
    type: "ONSITE",
    city: "Manado",
    province: "Sulawesi Utara",
    country: "Indonesia",
    venueName: "Hotel GrandWhizz Megamas - Ruang Soputan",
    address: "Hotel GrandWhizz Megamas - Ruang Soputan, Mega Trade Center, Kawasan Megamas Manado",
    contactPersonName: "Bp Lukas Max",
    contactPersonPhone: "081221314789",
    whatsappPhone: "6281221314789",
    bankName: "BCA",
    bankAccountNumber: "1700642492",
    bankAccountHolder: "Max Pierre / Jack Christian",
    youtubeChannelName: "Family Blessing Manado",
  },
  {
    name: "Family Blessing Kalimantan",
    slug: "family-blessing-kalimantan",
    type: "ONSITE",
    city: "Samarinda",
    province: "Kalimantan Timur",
    country: "Indonesia",
    venueName: "Hotel Diamond Samarinda - Ruang Kalimaya",
    address: "Hotel Diamond Samarinda - Ruang Kalimaya, Jln Lambung Mangkurat, Samarinda",
    contactPersonName: "Bp Theo",
    contactPersonPhone: "082154531335",
    whatsappPhone: "6282154531335",
    bankName: "BCA",
    bankAccountNumber: "7935793149",
    bankAccountHolder: "Prima Wahyuningtyas / Nani Purnomo",
    youtubeChannelName: "Family Blessing Samarinda",
  },
  {
    name: "Zoom Family Blessing Japan",
    slug: "zoom-family-blessing-japan",
    type: "ZOOM",
    city: "Japan",
    province: "-",
    country: "Japan",
    venueName: "Zoom Online",
    address: "Online via Zoom",
    contactPersonName: "Ibu Lena",
    contactPersonPhone: "+08 80-6123-7586",
    whatsappPhone: "818061237586",
    bankName: "BCA",
    bankAccountNumber: "1011375206",
    bankAccountHolder: "Lena Helen Koe",
    youtubeChannelName: "Family Blessing Yogyakarta",
    zoomInfo: "Zoom ID TBA",
  },
  {
    name: "Zoom Family Blessing Papua",
    slug: "zoom-family-blessing-papua",
    type: "ZOOM",
    city: "Papua",
    province: "Papua",
    country: "Indonesia",
    venueName: "Zoom Online",
    address: "Online via Zoom",
    contactPersonName: "Bp Robby",
    contactPersonPhone: "08113030185",
    whatsappPhone: "628113030185",
    bankName: null,
    bankAccountNumber: null,
    bankAccountHolder: null,
    youtubeChannelName: "Family Blessing Surabaya",
  },
  {
    name: "Zoom Family Blessing Malaysia",
    slug: "zoom-family-blessing-malaysia",
    type: "ZOOM",
    city: "Malaysia",
    province: "-",
    country: "Malaysia",
    venueName: "Zoom Online",
    address: "Online via Zoom",
    contactPersonName: "Bp Reza",
    contactPersonPhone: "081330899888 / +60178998970",
    whatsappPhone: "6281330899888",
    bankName: null,
    bankAccountNumber: null,
    bankAccountHolder: null,
    youtubeChannelName: "Family Blessing Malaysia",
  },
] as const;

export const defaultSiteSettings = {
  siteName: "Family Blessing",
  tagline: "A Place of Prayer, Worship, and God's Presence",
  description:
    "Persekutuan doa Kristen yang rindu melihat setiap keluarga mengalami pemulihan, pertumbuhan iman, dan lawatan Tuhan.",
  logoUrl: "/uploads/family-blessing-logo.png",
  faviconUrl: null,
  primaryPhone: null,
  primaryEmail: null,
  instagramUrl: null,
  youtubeUrl: null,
  facebookUrl: null,
  address: null,
  seoTitle: "Family Blessing",
  seoDescription:
    "Persekutuan doa Kristen yang rindu melihat setiap keluarga mengalami pemulihan, pertumbuhan iman, dan lawatan Tuhan.",
  ogImageUrl: null,
  maintenanceMode: false,
};

export const defaultPages = [
  {
    slug: "about",
    title: "Tentang Family Blessing",
    content:
      "Family Blessing adalah persekutuan doa Kristen yang hadir untuk membangun keluarga dalam doa, penyembahan, firman, dan persekutuan yang hangat. Konten ini dapat disesuaikan dari CMS ketika sejarah resmi dan detail pelayanan sudah siap.",
  },
  {
    slug: "vision_mission",
    title: "Visi dan Misi",
    content:
      "Kami rindu melihat setiap pribadi mengalami kasih Tuhan, bertumbuh dalam iman, dan menjadi berkat bagi keluarga, kota, dan bangsa.",
  },
  {
    slug: "pastor_profile",
    title: "Digembalai oleh Ev. Yeremia Chemby",
    content:
      "Ev. Yeremia Chemby melayani dengan hati untuk membawa jemaat semakin mengenal Tuhan melalui doa, penyembahan, dan pengajaran firman. Profil lengkap dapat diperbarui dari CMS.",
  },
  {
    slug: "giving_intro",
    title: "Persembahan dan Dukungan Pelayanan",
    content:
      "Setiap persembahan dikelola untuk menopang pelayanan dan menjadi saluran berkat. Informasi rekening tersedia pada halaman cabang masing-masing.",
  },
  {
    slug: "prayer_intro",
    title: "Kirim Pokok Doa",
    content:
      "Kami percaya doa memiliki kuasa. Tim pelayanan kami siap mendukung Anda dalam doa dengan penuh kerahasiaan dan kasih.",
  },
] as const;
